# PROCESSING INFO

[Beams]

do_beams : True
beam_types : Meerkat, SKA
vstart : 950
vend : 1400
space : 512

beams_outputfile : BeamData.hd5
beams_outputdir  : ./

# CLASS INFO

[Meerkat]

nside : 512
dish_diameter : 13.5 # m
aperture_taper_width : 200

dishes : 64
repeats : 36

[SKA]

nside : 512
dish_diameter : 15 # m
aperture_taper_width : 20

dishes : 133
repeats : 36